version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: glpi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - glpi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  glpi:
    image: rosnertech/glpi:10.0.18
    container_name: glpi-app
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - glpi-data:/var/www/html/glpi
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - glpi-network

volumes:
  db-data:
  glpi-data:

networks:
  glpi-network:
    driver: bridge
    